# coding: utf-8
import request.request_attachment as attachment_r
import pages.pages_attachment as attachment_p
import request.request_finance as finance_r
import pages.pages_finance as finance_p
import request.request_fulfillment as fulfillment_r
import pages.pages_fulfillment as fulfillment_p
import request.request_guarantee as guarantee_r
import pages.pages_guarantee as guarantee_p
import request.request_help as help_r
import pages.pages_help as help_p
import request.request_inventory as inventory_r
import pages.pages_inventory as inventory_p
import request.request_login as login_r
import pages.pages_login as login_p
import request.request_message as message_r
import pages.pages_message as message_p
import request.request_platform as platform_r
import pages.pages_platform as platform_p
import request.request_purchase as purchase_r
import pages.pages_purchase as purchase_p
import request.request_purse as purse_r
import pages.pages_purse as purse_p
import request.request_quality as quality_r
import pages.pages_quality as quality_p
import request.request_repair as repair_r
import pages.pages_repair as repair_p
import request.request_sell as sell_r
import pages.pages_sell as sell_p
import request.request_send as send_r
import pages.pages_send as send_p
import request.request_camera as camera_r

import request.request_auction as mg_r
import pages.pages_auction as mg_p
import request.request_trafficker as me_r
import request.request_bidding as mc_r
