# 首页
index = {
    "fast_shipping": {"xpath": "/view/view[4]/view[2]/view[1]"},
    "selling_price": {"xpath": "/view/view[1]/view[1]/view[3]/view[2]/input"},
    "committed": {"xpath": "/view/view[2]/view"},
    "precise_shipping": {"xpath": "/view/view[3]/view[2]/view[1]"},
    "model": {"xpath": "/view/view[3]/view/scroll-view/view[12]/view[4]"},
    "small_model": {"xpath": "/view/view[2]/view/view[2]/view[1]"},
    "purchase_channels": {"xpath": "/view/view[2]/view[2]/view[2]/view[1]"},
    "color": {"xpath": "/view/view[2]/view[3]/view[2]/view[1]"},
    "rom_capacity": {"xpath": "/view/view[2]/view[4]/view[2]/view[1]"},
    "next_step": {"xpath": "/view/view[3]/view"},
    "boot_situation": {"xpath": "/view/view[2]/view/view[2]/view[1]"},
    "account_lock": {"xpath": "/view/view[2]/view[2]/view[2]/view[1]"},
    "screen_appearance": {"xpath": "/view/view[2]/view[5]/view[2]/view[1]"},
    "lcd_display": {"xpath": "/view/view[2]/view[6]/view[2]/view[1]"},
    "body_appearance": {"xpath": "/view/view[2]/view[7]/view[2]/view[1]"},
    "battery_health": {"xpath": "/view/view[2]/view/view[2]/view[2]"},
    "front_facing_shooting_function": {"xpath": "/view/view[2]/view/view[3]/view[2]"},
    "get_an_instant_estimate": {"xpath": "/view/view[3]/view"},
    "confirm_submission": {"xpath": "/view/view[3]/view[2]"},
}
