"""PlaywrightCodeGenerator 单元测试 -- 从翻译后的操作生成完整 pytest Playwright 测试文件。

覆盖文件生成、元数据头部、语法验证、函数名净化、边界情况 (D-01 to D-06)。
"""

import ast
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from backend.core.action_translator import TranslatedAction
from backend.core.code_generator import PlaywrightCodeGenerator


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def generator() -> PlaywrightCodeGenerator:
    """每个测试创建新的 PlaywrightCodeGenerator 实例。"""
    return PlaywrightCodeGenerator()


def _make_actions() -> list[TranslatedAction]:
    """创建模拟 ERP 流程的翻译操作列表。"""
    return [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code='    page.locator("xpath=/html/body/div[2]/form/button").click()',
            action_type="click_element",
            is_comment=False,
            has_locator=True,
        ),
        TranslatedAction(
            code='    page.locator("xpath=/html/body/div[2]/form/input[1]").fill("test_user")',
            action_type="input_text",
            is_comment=False,
            has_locator=True,
        ),
        TranslatedAction(
            code="    page.mouse.wheel(0, 1000)",
            action_type="scroll",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code='    page.keyboard.press("Enter")',
            action_type="send_keys",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code="    page.go_back()",
            action_type="go_back",
            is_comment=False,
            has_locator=False,
        ),
    ]


# ---------------------------------------------------------------------------
# 文件生成测试
# ---------------------------------------------------------------------------


class TestGenerateCompleteFile:
    """完整文件生成测试。"""

    def test_generate_complete_file(self, generator: PlaywrightCodeGenerator) -> None:
        """生成包含所有操作类型的完整测试文件。"""
        actions = _make_actions()
        result = generator.generate(
            run_id="abc12345",
            task_name="销售出库流程",
            task_id="task001",
            actions=actions,
        )

        # 元数据头部 (D-04)
        assert "# Generated by aiDriveUITest" in result
        assert "# Task: 销售出库流程" in result
        assert "# Run ID: abc12345" in result
        assert "# Task ID: task001" in result
        assert "# Source: model_actions() from browser-use Agent" in result

        # Import 语句
        assert "from playwright.sync_api import Page" in result

        # 函数定义
        assert "def test_" in result

        # 操作内容
        assert "page.goto(" in result
        assert "page.locator(" in result
        assert "page.mouse.wheel(" in result
        assert "page.keyboard.press(" in result
        assert "page.go_back()" in result


class TestGeneratedCodeParses:
    """生成的代码必须是合法 Python。"""

    def test_generated_code_parses(self, generator: PlaywrightCodeGenerator) -> None:
        """ast.parse() 应成功解析生成的代码。"""
        actions = _make_actions()
        code = generator.generate(
            run_id="parse_test",
            task_name="解析测试",
            task_id="tid001",
            actions=actions,
        )

        tree = ast.parse(code)
        function_defs = [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
        assert len(function_defs) >= 1


class TestMetadataHeader:
    """元数据头部验证 (D-04)。"""

    def test_metadata_header(self, generator: PlaywrightCodeGenerator) -> None:
        """验证元数据头部包含所有必要字段。"""
        code = generator.generate(
            run_id="test_run_123",
            task_name="测试任务名称",
            task_id="task_abc",
            actions=_make_actions(),
        )

        assert "# Run ID: test_run_123" in code
        assert "# Task: 测试任务名称" in code
        assert "# Task ID: task_abc" in code
        # 时间戳包含年份
        assert "# Generated: " in code


class TestFunctionNameSanitization:
    """函数名净化测试 (D-03)。"""

    def test_chinese_task_name(self, generator: PlaywrightCodeGenerator) -> None:
        """中文任务名应保留在函数名中。"""
        code = generator.generate(
            run_id="r1",
            task_name="销售出库流程",
            task_id="t1",
            actions=[],
        )
        assert "test_销售出库流程" in code

    def test_special_chars_replaced(self, generator: PlaywrightCodeGenerator) -> None:
        """特殊字符应替换为下划线。"""
        code = generator.generate(
            run_id="r2",
            task_name="test with special! chars",
            task_id="t2",
            actions=[],
        )
        assert "!" not in code.split("def test_")[1].split("(")[0]
        assert " " not in code.split("def test_")[1].split("(")[0]

    def test_empty_task_name(self, generator: PlaywrightCodeGenerator) -> None:
        """空任务名应使用 test_unnamed。"""
        code = generator.generate(
            run_id="r3",
            task_name="",
            task_id="t3",
            actions=[],
        )
        assert "test_unnamed" in code


class TestEmptyActionList:
    """空操作列表测试。"""

    def test_empty_action_list(self, generator: PlaywrightCodeGenerator) -> None:
        """空操作列表应生成有效 Python，函数体仅有 docstring。"""
        code = generator.generate(
            run_id="empty_run",
            task_name="空任务",
            task_id="t_empty",
            actions=[],
        )

        # 必须是合法 Python
        tree = ast.parse(code)
        func_defs = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
        assert len(func_defs) == 1


class TestAllCommentActions:
    """全部操作为注释的测试。"""

    def test_all_comment_actions(self, generator: PlaywrightCodeGenerator) -> None:
        """全部注释操作应生成有效 Python。"""
        actions = [
            TranslatedAction(
                code="    # upload_file: /data/test.xlsx",
                action_type="upload_file",
                is_comment=True,
                has_locator=False,
            ),
        ]
        code = generator.generate(
            run_id="comment_run",
            task_name="注释任务",
            task_id="t_comment",
            actions=actions,
        )

        # 合法 Python
        ast.parse(code)
        # 包含注释
        assert "# upload_file: /data/test.xlsx" in code


class TestGenerateAndSave:
    """generate_and_save 文件写入测试。"""

    async def test_generate_and_save_creates_file(self, generator: PlaywrightCodeGenerator) -> None:
        """generate_and_save 应创建文件并返回路径。"""
        # 模拟 AgentHistoryList 的 model_actions()
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"navigate": {"url": "https://example.com"}, "interacted_element": None},
            {"go_back": {}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            code_path = await generator.generate_and_save(
                run_id="save_test",
                task_name="保存测试",
                task_id="t_save",
                agent_history=mock_history,
                base_dir=tmpdir,
            )

            # 文件存在
            assert os.path.exists(code_path)

            # 文件内容是合法 Python
            with open(code_path) as f:
                content = f.read()
            ast.parse(content)

            # 路径格式正确 (per D-10)
            assert "save_test" in code_path
            assert "generated" in code_path

    async def test_generate_and_save_empty_actions(self, generator: PlaywrightCodeGenerator) -> None:
        """model_actions() 返回空列表时应生成空函数文件。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = []

        with tempfile.TemporaryDirectory() as tmpdir:
            code_path = await generator.generate_and_save(
                run_id="empty_save",
                task_name="空操作",
                task_id="t_empty_save",
                agent_history=mock_history,
                base_dir=tmpdir,
            )

            assert os.path.exists(code_path)
            with open(code_path) as f:
                content = f.read()
            ast.parse(content)


# ---------------------------------------------------------------------------
# 回退定位器代码生成测试 (Phase 83 Plan 02)
# ---------------------------------------------------------------------------


def _make_fallback_actions() -> list[TranslatedAction]:
    """创建包含 try-except 回退代码的翻译操作列表。"""
    return [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code=(
                "    try:\n"
                '        page.locator("xpath=/html/body/div[2]/form/button").click()\n'
                "    except Exception as _e1:\n"
                '        _healer.warning("定位器回退: xpath=.../button 失败, 尝试 id=submit")\n'
                "        try:\n"
                '            page.locator("[id=\'submit\']").click()\n'
                "        except Exception as _e2:\n"
                '            _healer.error("定位器全部失败 [click_element]: ...")\n'
                '            raise HealerError(action_type="click_element", '
                'locators=("..."), original_error=str(_e2))'
            ),
            action_type="click_element",
            is_comment=False,
            has_locator=True,
            locators=(
                'page.locator("xpath=/html/body/div[2]/form/button")',
                "page.locator(\"[id='submit']\")",
            ),
        ),
        TranslatedAction(
            code="    page.mouse.wheel(0, 1000)",
            action_type="scroll",
            is_comment=False,
            has_locator=False,
        ),
    ]


def _make_no_fallback_actions() -> list[TranslatedAction]:
    """创建不含回退的操作列表 (所有 locators 为空)。"""
    return [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code='    page.locator("xpath=/html/body/button").click()',
            action_type="click_element",
            is_comment=False,
            has_locator=True,
        ),
    ]


class TestFallbackCodeGeneration:
    """Phase 83 Plan 02: 回退定位器在完整文件中的代码生成测试。"""

    def test_logging_import_present_when_locators_nonempty(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """当 actions 中有 TranslatedAction.locators 非空时，生成文件包含 import logging。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb01",
            task_name="回退测试",
            task_id="t_fb01",
            actions=actions,
        )
        assert "import logging" in code

    def test_healer_error_import_present_when_locators_nonempty(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """当 actions 中有 locators 非空时，生成文件包含 HealerError import。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb01b",
            task_name="回退测试",
            task_id="t_fb01b",
            actions=actions,
        )
        assert "from backend.core.healer_error import HealerError" in code

    def test_no_healer_error_import_when_all_locators_empty(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """当所有 locators 为空时，不包含 HealerError import。"""
        actions = _make_no_fallback_actions()
        code = generator.generate(
            run_id="fb01c",
            task_name="无回退测试",
            task_id="t_fb01c",
            actions=actions,
        )
        assert "HealerError" not in code

    def test_healer_logger_present_when_locators_nonempty(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """当 actions 中有 locators 非空时，函数体包含 _healer = logging.getLogger("healer")。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb02",
            task_name="回退测试",
            task_id="t_fb02",
            actions=actions,
        )
        assert '_healer = logging.getLogger("healer")' in code

    def test_no_logging_when_all_locators_empty(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """当所有 locators 为空时，不包含 logging 相关代码（保持 Phase 82 格式）。"""
        actions = _make_no_fallback_actions()
        code = generator.generate(
            run_id="fb03",
            task_name="无回退测试",
            task_id="t_fb03",
            actions=actions,
        )
        assert "import logging" not in code
        assert "_healer" not in code

    def test_multiline_code_preserved_in_body(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """多行 try-except 代码在 _build_body 中保留缩进和换行。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb04",
            task_name="多行测试",
            task_id="t_fb04",
            actions=actions,
        )
        # try-except 代码应包含缩进结构
        assert "    try:" in code
        assert "    except Exception as _e1:" in code

    def test_mixed_actions_file_parses(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """混合单行和多行 code 的 actions 列表生成的文件通过 ast.parse() 语法检查。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb05",
            task_name="混合测试",
            task_id="t_fb05",
            actions=actions,
        )
        tree = ast.parse(code)
        func_defs = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
        assert len(func_defs) == 1

    def test_fallback_complete_file_parses(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """包含 try-except 回退的完整文件通过 ast.parse() 语法检查。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb06",
            task_name="完整回退",
            task_id="t_fb06",
            actions=actions,
        )
        ast.parse(code)

    def test_body_blank_line_separator_preserved(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """_build_body 在不同操作类型间仍插入空行分隔（现有行为不变）。"""
        actions = _make_fallback_actions()
        code = generator.generate(
            run_id="fb07",
            task_name="分隔测试",
            task_id="t_fb07",
            actions=actions,
        )
        # navigate 和 click_element 之间应有空行
        # scroll 和 click_element 之间应有空行
        lines = code.split("\n")
        # 找到 page.goto 行
        goto_idx = None
        for i, line in enumerate(lines):
            if "page.goto" in line:
                goto_idx = i
                break
        assert goto_idx is not None
        # goto 后面应有空行（navigate -> click_element 类型变化）
        assert lines[goto_idx + 1] == ""


# ---------------------------------------------------------------------------
# LLM Healing 集成测试 (Phase 84 Plan 02)
# ---------------------------------------------------------------------------


class TestLLMHealingIntegration:
    """Phase 84: PlaywrightCodeGenerator + LLMHealer 集成测试。"""

    @pytest.fixture
    def mock_llm_healer(self) -> MagicMock:
        """创建 mock LLMHealer。"""
        with patch("backend.core.code_generator.LLMHealer") as mock_cls:
            mock_instance = MagicMock()
            mock_cls.return_value = mock_instance
            yield mock_instance

    async def test_elem_none_triggers_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """interacted_element=None 时触发 LLM healing。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_1"
            # 创建 DOM snapshot 文件
            dom_dir = Path(tmpdir) / run_id / "dom"
            dom_dir.mkdir(parents=True, exist_ok=True)
            (dom_dir / "step_1.txt").write_text("<html><button>Submit</button></html>")

            llm_config = {"model": "test", "api_key": "test-key"}

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_instance.heal.return_value = MagicMock(
                    success=True,
                    code_snippet='page.locator("button").click()',
                    raw_response="...",
                    locator="button",
                )
                mock_cls.return_value = mock_instance

                code_path = await generator.generate_and_save(
                    run_id=run_id,
                    task_name="修复测试",
                    task_id="t_heal1",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config=llm_config,
                )

                mock_instance.heal.assert_called_once()

    async def test_single_locator_triggers_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """只有 1 个定位器（仅 XPath）时触发 healing。"""
        mock_elem = MagicMock()
        mock_elem.x_path = "/html/body/button"
        mock_elem.node_name = "BUTTON"
        mock_elem.attributes = {}
        mock_elem.ax_name = None

        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": mock_elem},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_2"
            dom_dir = Path(tmpdir) / run_id / "dom"
            dom_dir.mkdir(parents=True, exist_ok=True)
            (dom_dir / "step_1.txt").write_text("<html><button>OK</button></html>")

            llm_config = {"model": "test", "api_key": "test-key"}

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_instance.heal.return_value = MagicMock(
                    success=True,
                    code_snippet='page.locator("button").click()',
                    raw_response="...",
                    locator="button",
                )
                mock_cls.return_value = mock_instance

                await generator.generate_and_save(
                    run_id=run_id,
                    task_name="单定位器修复",
                    task_id="t_heal2",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config=llm_config,
                )

                mock_instance.heal.assert_called_once()

    async def test_two_plus_locators_skip_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """2+ 个定位器的健康步骤不触发 healing。"""
        mock_elem = MagicMock()
        mock_elem.x_path = "/html/body/button"
        mock_elem.node_name = "BUTTON"
        mock_elem.attributes = {"id": "btn"}
        mock_elem.ax_name = None

        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": mock_elem},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_3"

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_cls.return_value = mock_instance

                await generator.generate_and_save(
                    run_id=run_id,
                    task_name="健康测试",
                    task_id="t_heal3",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                mock_instance.heal.assert_not_called()

    async def test_navigate_skips_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """navigate 操作不触发 healing。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"navigate": {"url": "https://example.com"}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_4"

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_cls.return_value = mock_instance

                await generator.generate_and_save(
                    run_id=run_id,
                    task_name="导航测试",
                    task_id="t_heal4",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                mock_instance.heal.assert_not_called()

    async def test_healing_success_embeds_code(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """LLM 修复成功时，生成文件包含 LLM-healed 代码。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_5"
            dom_dir = Path(tmpdir) / run_id / "dom"
            dom_dir.mkdir(parents=True, exist_ok=True)
            (dom_dir / "step_1.txt").write_text("<html><button>Submit</button></html>")

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_instance.heal.return_value = MagicMock(
                    success=True,
                    code_snippet='page.locator("button").click()',
                    raw_response="...",
                    locator="button",
                )
                mock_cls.return_value = mock_instance

                code_path = await generator.generate_and_save(
                    run_id=run_id,
                    task_name="成功修复",
                    task_id="t_heal5",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                content = Path(code_path).read_text()
                assert "LLM 修复" in content
                assert 'page.locator("button").click()' in content

    async def test_healing_failure_preserves_original(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """LLM 修复失败时，生成文件仍包含有效代码（原始占位符保留）。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_6"
            dom_dir = Path(tmpdir) / run_id / "dom"
            dom_dir.mkdir(parents=True, exist_ok=True)
            (dom_dir / "step_1.txt").write_text("<html><button>Submit</button></html>")

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_instance.heal.return_value = MagicMock(
                    success=False,
                    code_snippet="",
                    raw_response="timeout",
                    locator="",
                )
                mock_cls.return_value = mock_instance

                code_path = await generator.generate_and_save(
                    run_id=run_id,
                    task_name="失败修复",
                    task_id="t_heal6",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                content = Path(code_path).read_text()
                # 文件仍是合法 Python
                ast.parse(content)
                # 包含原始占位符
                assert "page.wait_for_timeout" in content or "TODO" in content

    async def test_missing_dom_skips_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """DOM snapshot 文件缺失时，跳过 healing 不报错。"""
        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"click_element": {"index": 5}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_7"
            # 不创建 DOM 文件

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()
                mock_cls.return_value = mock_instance

                code_path = await generator.generate_and_save(
                    run_id=run_id,
                    task_name="缺失DOM",
                    task_id="t_heal7",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                # heal 不被调用
                mock_instance.heal.assert_not_called()
                # 文件仍生成
                assert os.path.exists(code_path)

    async def test_full_file_with_mixed_healing(
        self, generator: PlaywrightCodeGenerator
    ) -> None:
        """混合操作（部分需 healing）生成的文件通过 ast.parse()。"""
        mock_elem = MagicMock()
        mock_elem.x_path = "/html/body/input"
        mock_elem.node_name = "INPUT"
        mock_elem.attributes = {}
        mock_elem.ax_name = None

        mock_history = MagicMock()
        mock_history.model_actions.return_value = [
            {"navigate": {"url": "https://example.com"}, "interacted_element": None},
            {"click_element": {"index": 5}, "interacted_element": None},
            {"input_text": {"index": 12, "text": "hello"}, "interacted_element": mock_elem},
            {"scroll": {"down": True, "pages": 1.0}, "interacted_element": None},
        ]

        with tempfile.TemporaryDirectory() as tmpdir:
            run_id = "heal_test_8"
            dom_dir = Path(tmpdir) / run_id / "dom"
            dom_dir.mkdir(parents=True, exist_ok=True)
            (dom_dir / "step_1.txt").write_text("<html></html>")
            (dom_dir / "step_2.txt").write_text("<html><button>Go</button></html>")
            (dom_dir / "step_3.txt").write_text("<html><input /></html>")

            with patch("backend.core.code_generator.LLMHealer") as mock_cls:
                mock_instance = AsyncMock()

                async def mock_heal(action_type, failed_locators, dom_snapshot, action_params):
                    if action_type == "click_element":
                        return MagicMock(
                            success=True,
                            code_snippet='page.locator("button").click()',
                            raw_response="...",
                            locator="button",
                        )
                    return MagicMock(
                        success=False,
                        code_snippet="",
                        raw_response="fail",
                        locator="",
                    )

                mock_instance.heal = mock_heal
                mock_cls.return_value = mock_instance

                code_path = await generator.generate_and_save(
                    run_id=run_id,
                    task_name="混合修复",
                    task_id="t_heal8",
                    agent_history=mock_history,
                    base_dir=tmpdir,
                    llm_config={"model": "test", "api_key": "key"},
                )

                content = Path(code_path).read_text()
                ast.parse(content)
