"""PlaywrightCodeGenerator unit tests -- slimmed.

Keeps 3 core tests:
  1. Code generation success path (all action types)
  2. Multi-opcode with fallback locators (file still valid Python)
  3. Error handling (LLM healing failure preserves valid code)
"""

import ast
import os
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from backend.core.action_translator import TranslatedAction
from backend.core.code_generator import PlaywrightCodeGenerator


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def generator() -> PlaywrightCodeGenerator:
    return PlaywrightCodeGenerator()


def _make_actions() -> list[TranslatedAction]:
    """Create mock ERP flow translated actions."""
    return [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code='    page.locator("xpath=/html/body/div[2]/form/button").click()',
            action_type="click",
            is_comment=False,
            has_locator=True,
        ),
        TranslatedAction(
            code='    page.locator("xpath=/html/body/div[2]/form/input[1]").fill("test_user")',
            action_type="input",
            is_comment=False,
            has_locator=True,
        ),
        TranslatedAction(
            code="    page.mouse.wheel(0, 1000)",
            action_type="scroll",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code='    page.keyboard.press("Enter")',
            action_type="send_keys",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code="    page.go_back()",
            action_type="go_back",
            is_comment=False,
            has_locator=False,
        ),
    ]


def _make_fallback_actions() -> list[TranslatedAction]:
    """Actions with try-except fallback locator code."""
    return [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code=(
                "    try:\n"
                '        page.locator("xpath=/html/body/div[2]/form/button").click()\n'
                "    except Exception as _e1:\n"
                '        _healer.warning("定位器回退: xpath=.../button 失败, 尝试 id=submit")\n'
                "        try:\n"
                '            page.locator("[id=\'submit\']").click()\n'
                "        except Exception as _e2:\n"
                '            _healer.error("定位器全部失败 [click]: ...")\n'
                '            raise HealerError(action_type="click", '
                'locators=("..."), original_error=str(_e2))'
            ),
            action_type="click",
            is_comment=False,
            has_locator=True,
            locators=(
                'page.locator("xpath=/html/body/div[2]/form/button")',
                "page.locator(\"[id='submit']\")",
            ),
        ),
        TranslatedAction(
            code="    page.mouse.wheel(0, 1000)",
            action_type="scroll",
            is_comment=False,
            has_locator=False,
        ),
    ]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_generate_complete_file(generator: PlaywrightCodeGenerator) -> None:
    """Code generation success: full file with all action types and metadata."""
    actions = _make_actions()
    result = generator.generate(
        run_id="abc12345",
        task_name="销售出库流程",
        task_id="task001",
        actions=actions,
    )

    # Metadata header
    assert "# Generated by aiDriveUITest" in result
    assert "# Task: 销售出库流程" in result
    assert "# Run ID: abc12345" in result

    # Import + function definition
    assert "from playwright.sync_api import Page" in result
    assert "def test_" in result

    # All action types present
    assert "page.goto(" in result
    assert "page.locator(" in result
    assert "page.mouse.wheel(" in result
    assert "page.keyboard.press(" in result
    assert "page.go_back()" in result


def test_fallback_complete_file_parses(generator: PlaywrightCodeGenerator) -> None:
    """Multi-opcode with fallback locators: try-except code produces valid Python."""
    actions = _make_fallback_actions()
    code = generator.generate(
        run_id="fb06",
        task_name="完整回退",
        task_id="t_fb06",
        actions=actions,
    )
    tree = ast.parse(code)
    func_defs = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
    assert len(func_defs) == 1
    assert "import logging" in code


async def test_healing_failure_preserves_original(generator: PlaywrightCodeGenerator) -> None:
    """Error handling: LLM healing failure still generates valid Python file."""
    mock_history = MagicMock()
    mock_history.model_actions.return_value = [
        {"click": {"index": 5}, "interacted_element": None},
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        run_id = "heal_test_6"
        dom_dir = Path(tmpdir) / run_id / "dom"
        dom_dir.mkdir(parents=True, exist_ok=True)
        (dom_dir / "step_1.txt").write_text("<html><button>Submit</button></html>")

        with patch("backend.core.code_generator.LLMHealer") as mock_cls:
            mock_instance = AsyncMock()
            mock_instance.heal.return_value = MagicMock(
                success=False,
                code_snippet="",
                raw_response="timeout",
                locator="",
            )
            mock_cls.return_value = mock_instance

            code_path = await generator.generate_and_save(
                run_id=run_id,
                task_name="失败修复",
                task_id="t_heal6",
                agent_history=mock_history,
                base_dir=tmpdir,
                llm_config={"model": "test", "api_key": "key"},
            )

            content = Path(code_path).read_text()
            ast.parse(content)
            assert os.path.exists(code_path)


# ---------------------------------------------------------------------------
# Phase 105 Plan 02: INDENT-01 indent fix + INDENT-03 validate_syntax integration
# ---------------------------------------------------------------------------


def test_build_body_indent_fix(generator: PlaywrightCodeGenerator) -> None:
    """INDENT-01: _build_body adds 4-space prefix to non-empty lines without it."""
    actions = [
        TranslatedAction(
            code='page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
    ]
    result = generator._build_body(actions)
    assert result == '    page.goto("https://erp.example.com")'


def test_build_body_preserves_already_indented(
    generator: PlaywrightCodeGenerator,
) -> None:
    """INDENT-01: _build_body does NOT double-indent already-indented lines."""
    actions = [
        TranslatedAction(
            code='    page.goto("https://erp.example.com")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
    ]
    result = generator._build_body(actions)
    assert result == '    page.goto("https://erp.example.com")'


def test_build_body_empty_actions(generator: PlaywrightCodeGenerator) -> None:
    """INDENT-01: _build_body with empty actions returns empty string."""
    result = generator._build_body([])
    assert result == ""


def test_build_body_mixed_indent_multiline(
    generator: PlaywrightCodeGenerator,
) -> None:
    """INDENT-01: mixed indent + multi-line try-except, blank separator preserved."""
    actions = [
        TranslatedAction(
            code='page.goto("url")',
            action_type="navigate",
            is_comment=False,
            has_locator=False,
        ),
        TranslatedAction(
            code=(
                "    try:\n"
                '        page.locator("xpath=//button").click()\n'
                "    except Exception as _e:"
            ),
            action_type="click",
            is_comment=False,
            has_locator=True,
        ),
    ]
    result = generator._build_body(actions)
    result_lines = result.split("\n")

    # First non-empty line must start with 4 spaces
    first_line = result_lines[0]
    assert first_line == "    page.goto(\"url\")"

    # Blank separator line between action types is preserved as empty
    assert "" in result_lines

    # The already-indented multi-line block is unchanged
    assert '        page.locator("xpath=//button").click()' in result
    assert "    except Exception as _e:" in result


def test_generate_calls_validate_syntax(
    generator: PlaywrightCodeGenerator,
) -> None:
    """INDENT-03: generate() calls validate_syntax on the output."""
    actions = _make_actions()
    with patch.object(generator, "validate_syntax", return_value=True) as mock_vs:
        result = generator.generate("r1", "test", "t1", actions)

    mock_vs.assert_called_once()
    # validate_syntax was called with the content string
    call_arg = mock_vs.call_args[0][0]
    assert "def test_" in call_arg
    # generate() still returns the content
    assert "def test_" in result


def test_generate_logs_warning_on_syntax_error(
    generator: PlaywrightCodeGenerator,
) -> None:
    """INDENT-03: generate() logs warning when validate_syntax returns False."""
    actions = _make_actions()

    with (
        patch.object(generator, "validate_syntax", return_value=False),
        patch("backend.core.code_generator.ast.parse", side_effect=SyntaxError("invalid syntax", ("<test>", 5, 1, "def broken("))),
        patch("backend.core.code_generator.logger") as mock_logger,
    ):
        result = generator.generate("r1", "test", "t1", actions)

    # Warning was logged containing the Chinese validation message
    mock_logger.warning.assert_called_once()
    call_args = mock_logger.warning.call_args[0][0]
    assert "语法验证失败" in call_args
    # generate() still returns content (does not raise)
    assert "def test_" in result


async def test_generate_and_save_validates_before_write() -> None:
    """INDENT-03: generate_and_save calls validate_syntax, writes file even on failure."""
    gen = PlaywrightCodeGenerator()
    mock_history = MagicMock()
    mock_history.model_actions.return_value = [
        {"navigate": {"url": "http://x"}, "interacted_element": None},
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        with patch.object(gen, "validate_syntax", return_value=False) as mock_vs:
            code_path = await gen.generate_and_save(
                run_id="vs_test",
                task_name="验证测试",
                task_id="t_vs",
                agent_history=mock_history,
                base_dir=tmpdir,
            )

        # validate_syntax was called (once in generate() + once in generate_and_save())
        assert mock_vs.call_count == 2

        # File was still written even when validate_syntax returned False
        assert os.path.exists(code_path)
        content = Path(code_path).read_text()
        assert "def test_" in content
